#!/usr/bin/env bash
set -euo pipefail
# Generated by scripts/build_bootstraps.py; edit scripts/remote_lifecycle.py.
command -v python3 >/dev/null || { echo "python3 is required." >&2; exit 1; }
command -v curl >/dev/null || { echo "curl is required." >&2; exit 1; }
python3 - install "$@" <<'BOOTSTRAP_PY'
"""Stdlib bootstrap embedded into both curl|bash entrypoints. No main fallback."""
import argparse
import json
import os
from pathlib import Path, PurePosixPath
import re
import shutil
import subprocess
import sys
import tarfile
import tempfile

REPOSITORY = 'wwintj/clash-yaml-manager'
INSTALL_DIR = Path('/opt/clash-yaml-manager')
SEMVER = r'(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)'


class LifecycleError(RuntimeError):
    pass


def version_tuple(value):
    if not re.fullmatch(SEMVER, value):
        raise LifecycleError('Invalid stable version; expected X.Y.Z or vX.Y.Z.')
    return tuple(map(int, value.split('.')))


def tag_name(value):
    if not isinstance(value, str):
        raise LifecycleError('Invalid release tag type.')
    version = value[1:] if value.startswith('v') else value
    version_tuple(version)
    return 'v' + version


def download(url, destination):
    result = subprocess.run([
        'curl', '--fail', '--silent', '--show-error', '--location',
        '--proto', '=https', '--proto-redir', '=https', '--connect-timeout', '10',
        '--max-time', '120', '--output', str(destination), '--write-out', '%{http_code}', url,
    ], capture_output=True, text=True)
    if result.returncode:
        status = result.stdout.strip()
        reason = {'404': 'Release not found', '403': 'GitHub access denied or API rate limit',
                  '429': 'GitHub API rate limit'}.get(status, 'Network/TLS/timeout or download error')
        raise LifecycleError(f'{reason} (HTTP {status or "unknown"}). Stopped; no main fallback.')


def resolve_release(directory, requested=None, fetch=download):
    endpoint = 'latest' if requested is None else 'tags/' + tag_name(requested)
    response = directory / 'release.json'
    fetch(f'https://api.github.com/repos/{REPOSITORY}/releases/{endpoint}', response)
    try:
        release = json.loads(response.read_text(encoding='utf-8'))
        tag = release['tag_name']
        if release.get('draft') is not False or release.get('prerelease') is not False:
            raise ValueError
        if tag_name(tag) != tag or (requested and tag != tag_name(requested)):
            raise ValueError
    except (KeyError, TypeError, ValueError, OSError, LifecycleError):
        raise LifecycleError('Malformed or non-stable GitHub Release response. Stopped.') from None
    return tag


def extract_archive(archive, directory, tag):
    """Manually extract only regular files/dirs after validating the entire archive."""
    try:
        with tarfile.open(archive, 'r:gz') as source:
            members = source.getmembers()
            if not members or len(members) > 10000 or sum(m.size for m in members) > 200 * 1024 * 1024:
                raise ValueError
            roots, names = set(), set()
            for member in members:
                path = PurePosixPath(member.name)
                if (path.is_absolute() or '..' in path.parts or '\\' in member.name or not path.parts
                        or not (member.isdir() or member.isfile()) or str(path) in names):
                    raise ValueError
                roots.add(path.parts[0])
                names.add(str(path))
            if len(roots) != 1:
                raise ValueError
            for member in members:
                target = directory / member.name
                if member.isdir():
                    target.mkdir(parents=True, exist_ok=True, mode=0o700)
                else:
                    target.parent.mkdir(parents=True, exist_ok=True, mode=0o700)
                    with source.extractfile(member) as incoming, target.open('xb') as outgoing:
                        shutil.copyfileobj(incoming, outgoing)
                    target.chmod(0o700 if member.mode & 0o111 else 0o600)
        root = directory / roots.pop()
        required = ('VERSION', 'app.py', 'requirements.txt', 'install.sh', 'update.sh',
                    'uninstall.sh', 'scripts/deploy-common.sh', 'core/security.py', 'core/version.py')
        if not all((root / name).is_file() for name in required):
            raise ValueError
        if (root / 'VERSION').read_text().rstrip('\n') != tag[1:]:
            raise ValueError
        for script in ('install.sh', 'update.sh', 'uninstall.sh', 'scripts/deploy-common.sh'):
            subprocess.run(['bash', '-n', str(root / script)], check=True, capture_output=True)
        return root
    except (tarfile.TarError, OSError, ValueError, subprocess.CalledProcessError):
        raise LifecycleError('Invalid release archive or VERSION/tag mismatch; nothing installed.') from None


def execute_script(root, mode):
    if mode == 'install':
        # curl|bash consumes stdin. Read port/password from the controlling TTY.
        try:
            terminal = open('/dev/tty', 'r')
        except OSError:
            raise LifecycleError('Installation needs a terminal for port and hidden password input.') from None
        with terminal:
            subprocess.run(['bash', 'install.sh'], cwd=root, stdin=terminal, check=True)
    else:
        subprocess.run(['bash', 'update.sh'], cwd=root, check=True)


def run_lifecycle(mode, args, install_dir=INSTALL_DIR, fetch=download, execute=execute_script):
    if not args.resolve_only and os.geteuid() != 0:
        raise LifecycleError('Please run with sudo/root.')
    if mode == 'update' and not args.resolve_only and not (install_dir / 'app.py').is_file():
        raise LifecycleError('Existing installation not found; use remote-install.sh.')
    with tempfile.TemporaryDirectory(prefix=f'clash-yaml-manager-{mode}-') as work:
        directory = Path(work)
        tag = resolve_release(directory, args.version, fetch)
        print(f'Resolved stable: {tag}', flush=True)
        if args.resolve_only:
            return tag
        if mode == 'update':
            installed = install_dir / 'VERSION'
            if installed.exists():
                current = installed.read_text().rstrip('\n')
                current_tuple, target_tuple = version_tuple(current), version_tuple(tag[1:])
                print(f'Installed version: {current}', flush=True)
                if current_tuple == target_tuple:
                    print('Already up to date.', flush=True)
                    return tag
                if target_tuple < current_tuple and not args.allow_downgrade:
                    raise LifecycleError('Downgrade refused; use --allow-downgrade explicitly.')
            else:
                print('Installed version: legacy (no VERSION); preserving existing data during migration.', flush=True)
        archive = directory / 'source.tar.gz'
        fetch(f'https://codeload.github.com/{REPOSITORY}/tar.gz/refs/tags/{tag}', archive)
        root = extract_archive(archive, directory / 'extracted', tag)
        execute(root, mode)
        if (install_dir / 'VERSION').read_text().rstrip('\n') != tag[1:]:
            raise LifecycleError('Installed VERSION verification failed; inspect deployment backup.')
        print(f'{mode.capitalize()} complete: {tag}', flush=True)
        return tag


def main(argv=None):
    parser = argparse.ArgumentParser(description='Install/update exact GitHub stable release tags.')
    parser.add_argument('mode', choices=('install', 'update'))
    parser.add_argument('--version', help='Pin a published stable release, vX.Y.Z or X.Y.Z')
    parser.add_argument('--allow-downgrade', action='store_true')
    parser.add_argument('--resolve-only', action='store_true', help='Read-only stable tag lookup; no root needed')
    args = parser.parse_args(argv)
    if args.mode == 'install' and args.allow_downgrade:
        parser.error('--allow-downgrade applies only to update')
    try:
        run_lifecycle(args.mode, args)
    except (LifecycleError, OSError, subprocess.CalledProcessError) as error:
        parser.exit(1, f'{error}\n')


if __name__ == '__main__':
    main()
BOOTSTRAP_PY
