#!/usr/bin/env bash
set -euo pipefail
# Generated by scripts/build_bootstraps.py; edit scripts/remote_lifecycle.py.
command -v python3 >/dev/null || { echo "python3 is required." >&2; exit 1; }
command -v curl >/dev/null || { echo "curl is required." >&2; exit 1; }
python3 - update "$@" <<'BOOTSTRAP_PY'
"""Stdlib bootstrap embedded into both curl|bash entrypoints. Stable by default; main requires explicit selection."""
import argparse
import json
import os
from pathlib import Path, PurePosixPath
import re
import shutil
import subprocess
import sys
import tarfile
import tempfile

if __name__ == '__main__' and __file__ != '<stdin>':
    sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

"""Public build identity, separate from credentials and the stable VERSION source.

This stdlib-only module is also embedded into the standalone remote bootstraps.
INSTALLATION.json is root-owned/readable by the service, outside private auth state.
"""
from datetime import datetime, timezone
import json
import os
from pathlib import Path
import re
import tempfile

INSTALL_INFO_FILE = 'INSTALLATION.json'
_VERSION_PATTERN = r'(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)'
_COMMIT_PATTERN = r'[0-9a-f]{40}'


def validate_install_info(info, base_version=None):
    try:
        expected = {'channel', 'base_version', 'commit', 'tag', 'installed_at', 'source'}
        if not isinstance(info, dict) or set(info) != expected:
            raise ValueError
        version, channel = info['base_version'], info['channel']
        if not isinstance(version, str) or not re.fullmatch(_VERSION_PATTERN, version):
            raise ValueError
        if base_version is not None and version != base_version:
            raise ValueError
        if channel not in ('stable', 'main', 'local'):
            raise ValueError
        if channel == 'local':
            if info['commit'] is not None or info['tag'] is not None or info['source'] != 'local-source':
                raise ValueError
        else:
            if not isinstance(info['commit'], str) or not re.fullmatch(_COMMIT_PATTERN, info['commit']):
                raise ValueError
            if info['tag'] != ('v' + version if channel == 'stable' else None):
                raise ValueError
            if info['source'] != ('github-release' if channel == 'stable' else 'github-main'):
                raise ValueError
        timestamp = datetime.fromisoformat(info['installed_at'])
        if timestamp.tzinfo is None:
            raise ValueError
    except (KeyError, TypeError, ValueError):
        raise ValueError('Invalid installation metadata; inspect INSTALLATION.json before updating.') from None
    return info


def make_install_info(channel, base_version, commit=None, tag=None):
    return validate_install_info(dict(channel=channel, base_version=base_version, commit=commit,
        tag=tag, installed_at=datetime.now(timezone.utc).isoformat(timespec='seconds'),
        source={'stable':'github-release', 'main':'github-main', 'local':'local-source'}[channel]))


def read_install_info(directory, base_version=None):
    path = Path(directory) / INSTALL_INFO_FILE
    if not path.exists() and not path.is_symlink():
        return None
    if path.is_symlink():
        raise ValueError('Invalid installation metadata path.')
    try:
        return validate_install_info(json.loads(path.read_text(encoding='utf-8')), base_version)
    except (OSError, ValueError):
        raise ValueError('Invalid installation metadata; inspect INSTALLATION.json before updating.') from None


def write_install_info(directory, info):
    """Publish complete, credential-free metadata atomically before service startup."""
    validate_install_info(info)
    directory = Path(directory)
    path = directory / INSTALL_INFO_FILE
    if path.is_symlink():
        raise ValueError('Invalid installation metadata path.')
    fd, temporary = tempfile.mkstemp(prefix='.installation-', dir=directory)
    try:
        with os.fdopen(fd, 'w', encoding='utf-8') as target:
            json.dump(info, target, sort_keys=True)
            target.write('\n')
            target.flush()
            os.fchmod(target.fileno(), 0o644)  # Public build data; never auth material.
            os.fsync(target.fileno())
        os.replace(temporary, path)
        parent = os.open(directory, os.O_RDONLY)
        try:
            os.fsync(parent)
        finally:
            os.close(parent)
    finally:
        if os.path.exists(temporary):
            os.unlink(temporary)


def display_build(base_version, info=None):
    if info is None:
        return base_version
    validate_install_info(info, base_version)
    if info['channel'] == 'main':
        return base_version + '-dev+' + info['commit'][:7]
    if info['channel'] == 'local':
        return base_version + '-local'
    return base_version


def finalize_install(directory):
    """Called by install/update before ownership repair and service restart.

    The remote bootstrap passes a private metadata path, never credentials. Direct
    local-source deployments get an honest local identity instead of retaining a
    stale main commit. Old stable scripts are supported by bootstrap finalization.
    """
    directory = Path(directory)
    version = (directory / 'VERSION').read_text().rstrip('\n')
    incoming = os.environ.get('CLASH_DEPLOY_METADATA')
    if incoming:
        path = Path(incoming)
        if path.is_symlink():
            raise ValueError('Invalid deployment metadata path.')
        info = validate_install_info(json.loads(path.read_text()), version)
    else:
        info = make_install_info('local', version)
    write_install_info(directory, info)
    print('Installed build: ' + display_build(version, info))

"""Root-only admission for participating updaters, including remote finalization.

This module is also embedded into the two standalone bootstraps. Never unlink
the persistent directory or lock file. Closing references releases flock; an
explicit LOCK_UN would incorrectly unlock a parent's inherited description.
"""
from contextlib import contextmanager
from contextvars import ContextVar
from functools import wraps
import errno
import fcntl
import os
import stat
import subprocess
import sys

GUARD_ROOT = '/var/lib/clash-yaml-manager-deployment'
GUARD_NAME = 'update.lock'
GUARD_UID = 0
GUARD_GID = 0
GUARD_ENV = 'CLASH_DEPLOYMENT_GUARD_FDS'
GUARD_CONFLICT_EXIT = 75
GUARD_UNSAFE_EXIT = 78
GUARD_ACTIVE = ContextVar('deployment_guard', default=None)


class DeploymentGuardError(RuntimeError):
    def __init__(self, code):
        super().__init__(code)
        self.code = code
        self.exit_code = GUARD_CONFLICT_EXIT if code == 'DEPLOYMENT_GUARD_CONFLICT' else GUARD_UNSAFE_EXIT


def guard_require(condition, code='DEPLOYMENT_GUARD_UNSAFE'):
    if not condition:
        raise DeploymentGuardError(code)


def guard_require_root():
    guard_require(os.geteuid() == 0, 'DEPLOYMENT_GUARD_ROOT_REQUIRED')


def guard_io(function):
    @wraps(function)
    def checked(*args, **kwargs):
        try:
            return function(*args, **kwargs)
        except OSError:
            raise DeploymentGuardError('DEPLOYMENT_GUARD_UNAVAILABLE') from None
    return checked


def guard_identity(info):
    return info.st_dev, info.st_ino, stat.S_IFMT(info.st_mode)


def guard_ancestor(info):
    # Root-owned sticky ancestors also protect root-owned children (/tmp in
    # native isolated fixtures). The fixed production ancestors are /var/lib.
    guard_require(stat.S_ISDIR(info.st_mode) and info.st_uid in (0, GUARD_UID))
    guard_require(not info.st_mode & 0o022 or bool(info.st_mode & stat.S_ISVTX))


def guard_private(info, directory=False):
    guard_require((stat.S_ISDIR(info.st_mode) if directory else stat.S_ISREG(info.st_mode))
                  and info.st_uid == GUARD_UID and info.st_gid == GUARD_GID
                  and stat.S_IMODE(info.st_mode) == (0o700 if directory else 0o600))
    if not directory:
        guard_require(info.st_nlink == 1 and info.st_size == 0)


def guard_flags(directory=False):
    names = ('O_NOFOLLOW', 'O_NONBLOCK', 'O_CLOEXEC', 'O_DIRECTORY')
    guard_require(all(hasattr(os, name) for name in names), 'DEPLOYMENT_GUARD_UNAVAILABLE')
    return (os.O_RDONLY if directory else os.O_RDWR) | os.O_NOFOLLOW | os.O_NONBLOCK | os.O_CLOEXEC | (os.O_DIRECTORY if directory else 0)


@guard_io
def guard_open_root(create=False):
    guard_require(isinstance(GUARD_ROOT, str) and GUARD_ROOT.startswith('/')
                  and len(GUARD_ROOT.encode()) <= 1024 and len(GUARD_ROOT.split('/')) <= 32
                  and all(p not in ('.', '..', '') for p in GUARD_ROOT.split('/')[1:]))
    pieces = GUARD_ROOT.split('/')[1:]
    fd = os.open('/', guard_flags(True))
    try:
        guard_ancestor(os.fstat(fd))
        for piece in pieces[:-1]:
            before = os.stat(piece, dir_fd=fd, follow_symlinks=False)
            guard_ancestor(before)
            following = os.open(piece, guard_flags(True), dir_fd=fd)
            try:
                guard_require(guard_identity(before) == guard_identity(os.fstat(following)))
            except BaseException:
                os.close(following)
                raise
            os.close(fd)
            fd = following
        made = False
        if create:
            try:
                os.mkdir(pieces[-1], 0o700, dir_fd=fd)
                made = True
            except FileExistsError:
                pass
        before = os.stat(pieces[-1], dir_fd=fd, follow_symlinks=False)
        guard_require(stat.S_ISDIR(before.st_mode) and before.st_uid == GUARD_UID and before.st_gid == GUARD_GID)
        root = os.open(pieces[-1], guard_flags(True), dir_fd=fd)
        try:
            guard_require(guard_identity(before) == guard_identity(os.fstat(root)))
            if made:
                os.fchmod(root, 0o700)  # Only the directory this call exclusively created.
                os.fsync(root)
                os.fsync(fd)
            guard_private(os.fstat(root), True)
        except BaseException:
            os.close(root)
            raise
        return root
    finally:
        os.close(fd)


def guard_flock(fd):
    try:
        fcntl.flock(fd, fcntl.LOCK_EX | fcntl.LOCK_NB)
    except OSError as error:
        if error.errno in (errno.EAGAIN, errno.EWOULDBLOCK):
            raise DeploymentGuardError('DEPLOYMENT_GUARD_CONFLICT') from None
        raise DeploymentGuardError('DEPLOYMENT_GUARD_UNAVAILABLE') from None


class DeploymentGuard:
    def __init__(self, directory, lock):
        self.directory, self.lock = directory, lock
        self.directory_identity = guard_identity(os.fstat(directory))
        self.lock_identity = guard_identity(os.fstat(lock))

    @guard_io
    def validate(self):
        guard_private(os.fstat(self.directory), True)
        guard_private(os.fstat(self.lock))
        guard_require(guard_identity(os.fstat(self.directory)) == self.directory_identity
                      and guard_identity(os.fstat(self.lock)) == self.lock_identity,
                      'DEPLOYMENT_GUARD_CHANGED')
        current = guard_open_root()
        try:
            guard_require(guard_identity(os.fstat(current)) == self.directory_identity,
                          'DEPLOYMENT_GUARD_CHANGED')
            info = os.stat(GUARD_NAME, dir_fd=current, follow_symlinks=False)
            guard_private(info)
            guard_require(guard_identity(info) == self.lock_identity
                          and info.st_dev == os.fstat(current).st_dev,
                          'DEPLOYMENT_GUARD_CHANGED')
        finally:
            os.close(current)
        # This succeeds for the same inherited open-file description, but
        # refuses a forged fresh descriptor while another holder owns the lock.
        guard_flock(self.directory)
        guard_flock(self.lock)

    def environment(self, environ):
        self.validate()
        result = dict(environ)
        result[GUARD_ENV] = f'{self.directory}:{self.lock}'
        return result

    def close(self):
        failure = None
        for fd in (self.lock, self.directory):
            try:
                os.close(fd)
            except OSError:
                failure = DeploymentGuardError('DEPLOYMENT_GUARD_UNAVAILABLE')
        if failure:
            raise failure


@guard_io
def guard_acquire():
    guard_require_root()
    directory, lock = guard_open_root(True), None
    try:
        # Directory locking also excludes a second participating updater if a
        # privileged external actor replaces the lock file during this lease.
        guard_flock(directory)
        made = False
        try:
            lock = os.open(GUARD_NAME, guard_flags() | os.O_CREAT | os.O_EXCL, 0o600, dir_fd=directory)
            made = True
        except FileExistsError:
            before = os.stat(GUARD_NAME, dir_fd=directory, follow_symlinks=False)
            guard_private(before)
            lock = os.open(GUARD_NAME, guard_flags(), dir_fd=directory)
            guard_require(guard_identity(before) == guard_identity(os.fstat(lock)), 'DEPLOYMENT_GUARD_CHANGED')
        if made:
            os.fchmod(lock, 0o600)
            os.fsync(lock)
            os.fsync(directory)
        guard_private(os.fstat(lock))
        guard_flock(lock)
        result = DeploymentGuard(directory, lock)
        result.validate()
        return result
    except BaseException:
        if lock is not None:
            os.close(lock)
        os.close(directory)
        raise


@guard_io
def guard_inherited(environ):
    guard_require_root()
    value = environ.get(GUARD_ENV, '')
    guard_require(isinstance(value, str) and len(value) <= 23, 'DEPLOYMENT_GUARD_BAD_HANDOFF')
    fields = value.split(':')
    guard_require(len(fields) == 2 and all(p.isascii() and p.isdigit() and len(p) <= 10 for p in fields),
                  'DEPLOYMENT_GUARD_BAD_HANDOFF')
    directory, lock = map(int, fields)
    guard_require(3 <= directory <= 2**31 - 1 and 3 <= lock <= 2**31 - 1
                  and directory != lock, 'DEPLOYMENT_GUARD_BAD_HANDOFF')
    duplicate_directory = os.dup(directory)
    try:
        duplicate_lock = os.dup(lock)
        try:
            result = DeploymentGuard(duplicate_directory, duplicate_lock)
            result.validate()
            return result
        except BaseException:
            os.close(duplicate_lock)
            raise
    except BaseException:
        os.close(duplicate_directory)
        raise


@contextmanager
def held_deployment_guard():
    # Remote admission always acquires independently. Environment cannot supply
    # an unchecked "already locked" assertion to skip this acquisition.
    handle = guard_acquire()
    token = GUARD_ACTIVE.set(handle)
    try:
        yield handle
        handle.validate()
    finally:
        GUARD_ACTIVE.reset(token)
        handle.close()


def current_deployment_guard():
    handle = GUARD_ACTIVE.get()
    guard_require(handle is not None, 'DEPLOYMENT_GUARD_BAD_HANDOFF')
    handle.validate()
    return handle


def deployment_guard_main(argv=None):
    sys.dont_write_bytecode = True
    args = list(sys.argv[1:] if argv is None else argv)
    try:
        if args == ['--check-inherited']:
            handle = guard_inherited(os.environ)
            handle.close()  # Close duplicates only; never LOCK_UN the parent.
            return 0
        guard_require(len(args) >= 2 and args[0] == '--run-update', 'DEPLOYMENT_GUARD_ARGUMENTS')
        with held_deployment_guard() as handle:
            result = subprocess.run(['bash', args[1], *args[2:]], env=handle.environment(os.environ),
                                    pass_fds=(handle.directory, handle.lock))
            return result.returncode if result.returncode >= 0 else 128 - result.returncode
    except DeploymentGuardError as error:
        print('Deployment guard refused: ' + error.code, file=sys.stderr)
        return error.exit_code
    except (OSError, ValueError, TypeError):
        print('Deployment guard refused: DEPLOYMENT_GUARD_UNAVAILABLE', file=sys.stderr)
        return GUARD_UNSAFE_EXIT



REPOSITORY = 'wwintj/clash-yaml-manager'
INSTALL_DIR = Path('/opt/clash-yaml-manager')
SEMVER = r'(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)'


class LifecycleError(RuntimeError):
    pass


def version_tuple(value):
    if not re.fullmatch(SEMVER, value):
        raise LifecycleError('Invalid stable version; expected X.Y.Z or vX.Y.Z.')
    return tuple(map(int, value.split('.')))


def tag_name(value):
    if not isinstance(value, str):
        raise LifecycleError('Invalid release tag type.')
    version = value[1:] if value.startswith('v') else value
    version_tuple(version)
    return 'v' + version


def download(url, destination):
    result = subprocess.run([
        'curl', '--fail', '--silent', '--show-error', '--location',
        '--proto', '=https', '--proto-redir', '=https', '--connect-timeout', '10',
        '--max-time', '120', '--output', str(destination), '--write-out', '%{http_code}', url,
    ], capture_output=True, text=True)
    if result.returncode:
        status = result.stdout.strip()
        reason = {'404': 'Release not found', '403': 'GitHub access denied or API rate limit',
                  '429': 'GitHub API rate limit'}.get(status, 'Network/TLS/timeout or download error')
        raise LifecycleError(f'{reason} (HTTP {status or "unknown"}). Stopped; no main fallback.')


def resolve_release(directory, requested=None, fetch=download):
    endpoint = 'latest' if requested is None else 'tags/' + tag_name(requested)
    response = directory / 'release.json'
    fetch(f'https://api.github.com/repos/{REPOSITORY}/releases/{endpoint}', response)
    try:
        release = json.loads(response.read_text(encoding='utf-8'))
        tag = release['tag_name']
        if release.get('draft') is not False or release.get('prerelease') is not False:
            raise ValueError
        if tag_name(tag) != tag or (requested and tag != tag_name(requested)):
            raise ValueError
    except (KeyError, TypeError, ValueError, OSError, LifecycleError):
        raise LifecycleError('Malformed or non-stable GitHub Release response. Stopped.') from None
    return tag


def extract_archive(archive, directory, tag=None):
    """Manually extract only regular files/dirs after validating the entire archive."""
    try:
        with tarfile.open(archive, 'r:gz') as source:
            members = source.getmembers()
            if not members or len(members) > 10000 or sum(m.size for m in members) > 200 * 1024 * 1024:
                raise ValueError
            roots, names = set(), set()
            for member in members:
                path = PurePosixPath(member.name)
                if (path.is_absolute() or '..' in path.parts or '\\' in member.name or not path.parts
                        or not (member.isdir() or member.isfile()) or str(path) in names):
                    raise ValueError
                roots.add(path.parts[0])
                names.add(str(path))
            if len(roots) != 1:
                raise ValueError
            for member in members:
                target = directory / member.name
                if member.isdir():
                    target.mkdir(parents=True, exist_ok=True, mode=0o700)
                else:
                    target.parent.mkdir(parents=True, exist_ok=True, mode=0o700)
                    with source.extractfile(member) as incoming, target.open('xb') as outgoing:
                        shutil.copyfileobj(incoming, outgoing)
                    target.chmod(0o700 if member.mode & 0o111 else 0o600)
        root = directory / roots.pop()
        required = ('VERSION', 'app.py', 'requirements.txt', 'install.sh', 'update.sh',
                    'uninstall.sh', 'scripts/deploy-common.sh', 'core/security.py', 'core/version.py')
        if not all((root / name).is_file() for name in required):
            raise ValueError
        base_version = (root / 'VERSION').read_text().rstrip('\n')
        version_tuple(base_version)
        if tag is not None and base_version != tag[1:]:
            raise ValueError
        for script in ('install.sh', 'update.sh', 'uninstall.sh', 'scripts/deploy-common.sh'):
            subprocess.run(['bash', '-n', str(root / script)], check=True, capture_output=True)
        return root
    except (tarfile.TarError, OSError, ValueError, LifecycleError, subprocess.CalledProcessError):
        raise LifecycleError('Invalid release archive or VERSION/tag mismatch; nothing installed.') from None


def execute_script(root, mode, metadata):
    env = dict(os.environ, CLASH_DEPLOY_METADATA=str(metadata))
    if mode == 'install':
        # curl|bash consumes stdin. Read port/password from the controlling TTY.
        try:
            terminal = open('/dev/tty', 'r')
        except OSError:
            raise LifecycleError('Installation needs a terminal for port and hidden password input.') from None
        with terminal:
            subprocess.run(['bash', 'install.sh'], cwd=root, stdin=terminal, check=True, env=env)
    else:
        guard = current_deployment_guard()
        subprocess.run(['bash', 'update.sh'], cwd=root, check=True, env=guard.environment(env),
                       pass_fds=(guard.directory, guard.lock))


def resolve_commit(directory, channel, tag=None, fetch=download):
    response = directory / 'commit.json'
    endpoint = 'git/ref/heads/main' if channel == 'main' else 'commits/' + tag
    fetch(f'https://api.github.com/repos/{REPOSITORY}/{endpoint}', response)
    try:
        value = json.loads(response.read_text(encoding='utf-8'))
        if channel == 'main':
            if value['ref'] != 'refs/heads/main' or value['object']['type'] != 'commit':
                raise ValueError
            commit = value['object']['sha']
        else:
            commit = value['sha']
        if not isinstance(commit, str) or not re.fullmatch(r'[0-9a-f]{40}', commit):
            raise ValueError
    except (KeyError, TypeError, ValueError, OSError):
        raise LifecycleError('Malformed GitHub commit response. Stopped; no channel fallback.') from None
    return commit


def run_lifecycle(mode, args, install_dir=INSTALL_DIR, fetch=download, execute=execute_script):
    channel = getattr(args, 'channel', 'stable')
    if channel not in ('stable', 'main'):
        raise LifecycleError('Invalid channel; choose stable or main.')
    if channel == 'main' and args.version:
        raise LifecycleError('--version cannot be combined with --channel main')
    if not args.resolve_only and os.geteuid() != 0:
        raise LifecycleError('Please run with sudo/root.')
    if mode == 'update' and not args.resolve_only and not (install_dir / 'app.py').is_file():
        raise LifecycleError('Existing installation not found; use remote-install.sh.')
    if mode == 'update' and not args.resolve_only:
        with held_deployment_guard():
            return _run_lifecycle(mode, args, install_dir, fetch, execute)
    return _run_lifecycle(mode, args, install_dir, fetch, execute)


def _run_lifecycle(mode, args, install_dir, fetch, execute):
    channel = getattr(args, 'channel', 'stable')
    print(f'Channel: {channel}', flush=True)
    if channel == 'main':
        print('Development channel selected. This build is not a Stable Release.', flush=True)
    with tempfile.TemporaryDirectory(prefix=f'clash-yaml-manager-{mode}-') as work:
        directory = Path(work)
        tag = resolve_release(directory, args.version, fetch) if channel == 'stable' else None
        commit = resolve_commit(directory, channel, fetch=fetch) if channel == 'main' else None
        if tag:
            print(f'Resolved stable: {tag}', flush=True)
        if commit:
            print(f'Resolved commit: {commit}', flush=True)
        if args.resolve_only:
            return tag or commit
        current, installed_info = None, None
        if mode == 'update':
            installed = install_dir / 'VERSION'
            if installed.exists():
                current = installed.read_text().rstrip('\n')
                version_tuple(current)
                try:
                    installed_info = read_install_info(install_dir, current)
                except ValueError as error:
                    raise LifecycleError(str(error)) from None
                installed_channel = installed_info['channel'] if installed_info else 'stable'
                print('Installed build: ' + display_build(current, installed_info), flush=True)
                if installed_channel != channel:
                    print(f'Switching channel: {installed_channel} → {channel}', flush=True)
                if channel == 'main':
                    print('Installed commit: ' + str(installed_info['commit'] if installed_info else 'unknown'), flush=True)
                    print('Remote main commit: ' + commit, flush=True)
                    if installed_channel == 'main' and installed_info['commit'] == commit:
                        print('Already up to date.', flush=True)
                        return commit
                else:
                    current_tuple, target_tuple = version_tuple(current), version_tuple(tag[1:])
                    if installed_channel in ('main', 'local') and target_tuple <= current_tuple and not args.allow_downgrade:
                        raise LifecycleError('A development build is currently installed. Latest Stable is based on an older '
                            'or equal release. Refusing automatic channel downgrade; use --channel stable --allow-downgrade.')
                    if installed_channel == 'stable' and current_tuple == target_tuple:
                        print('Already up to date.', flush=True)
                        return tag
                    if target_tuple < current_tuple and not args.allow_downgrade:
                        raise LifecycleError('Downgrade refused; use --allow-downgrade explicitly.')
            else:
                if (install_dir / 'INSTALLATION.json').exists():
                    raise LifecycleError('Installation metadata exists without VERSION; inspect deployment backup.')
                print('Installed version: legacy (no VERSION); preserving existing data during migration.', flush=True)
        if commit is None:
            commit = resolve_commit(directory, 'stable', tag, fetch)
            print(f'Resolved commit: {commit}', flush=True)
        archive = directory / 'source.tar.gz'
        # Both channels download immutable commits; stable commits come only from Releases.
        fetch(f'https://codeload.github.com/{REPOSITORY}/tar.gz/{commit}', archive)
        root = extract_archive(archive, directory / 'extracted', tag)
        base_version = (root / 'VERSION').read_text().rstrip('\n')
        print(f'Base version: {base_version}', flush=True)
        info = make_install_info(channel, base_version, commit, tag)
        # Keep deployment data outside the source archive and out of .env.
        write_install_info(directory, info)
        execute(root, mode, directory / 'INSTALLATION.json')
        if (install_dir / 'VERSION').read_text().rstrip('\n') != base_version:
            raise LifecycleError('Installed VERSION verification failed; inspect deployment backup.')
        # Old stable lifecycle scripts predate metadata hooks. Finalize those too.
        if mode == 'update':
            current_deployment_guard().validate()
        write_install_info(install_dir, info)
        if read_install_info(install_dir, base_version) != info:
            raise LifecycleError('Installed build metadata verification failed.')
        print('Installed build: ' + display_build(base_version, info), flush=True)
        print(f'{mode.capitalize()} complete: {tag or commit}', flush=True)
        return tag or commit


def main(argv=None):
    parser = argparse.ArgumentParser(description='Install/update Stable by default; explicitly select main for development testing.')
    parser.add_argument('mode', choices=('install', 'update'))
    parser.add_argument('--channel', choices=('stable', 'main'), default='stable')
    parser.add_argument('--version', help='Pin a published stable release, vX.Y.Z or X.Y.Z')
    parser.add_argument('--allow-downgrade', action='store_true')
    parser.add_argument('--resolve-only', action='store_true', help='Read-only stable tag lookup; no root needed')
    args = parser.parse_args(argv)
    if args.channel == 'main' and args.version:
        parser.error('--version cannot be combined with --channel main')
    if args.mode == 'install' and args.allow_downgrade:
        parser.error('--allow-downgrade applies only to update')
    try:
        run_lifecycle(args.mode, args)
    except DeploymentGuardError as error:
        parser.exit(error.exit_code, 'Deployment guard refused: ' + error.code + '\n')
    except (LifecycleError, ValueError, OSError, subprocess.CalledProcessError) as error:
        parser.exit(1, f'{error}\n')


if __name__ == '__main__':
    main()
BOOTSTRAP_PY
