"""Exact generated bytes, private read-only previews and bounded text output."""
import copy
import hashlib
import io
import json
import logging
import os
import re
import socket
import subprocess
from concurrent.futures import ThreadPoolExecutor
from pathlib import Path

import pytest
from core import generator, yaml_diff, yaml_utils, policy_engine
from conftest import LINK, ROOT, post
from test_geoip import readers

SOURCE = '# retained header\ndns: {enable: true, nameserver: ["1.1.1.1"]}\nproxies: [{name: old, type: vless, server: old.example, port: 443, uuid: fake}]\nproxy-groups: [{name: custom, type: select, proxies: [old, DIRECT]}]\nrules: [MATCH,DIRECT]\nx-private: "<script>alert(1)</script> & Ω"\n'
BEFORE_HASHES = {'custom': '77812738ec3a51c8f160cacedc24dc97a9e9d3eeabc7bb0c2db78cc2dd222fda', 'default': '3c491ae173585c7a42ceadd4d8634753f38d932a36d92aac0ef7bb16a7e80a69'}
ROUTE = '/api/preview-yaml-diff'


def token(client):
    return re.search(r'name="csrf_token" value="([^"]+)"',client.get('/').text)[1]


def fields(source='custom', kind='preserve', overrides=None, geo='off', batch=None):
    return dict(yaml_source=source, batch_nodes=batch or 'US|Test|'+LINK,
                aux_nodes='[]', node_overrides=json.dumps(overrides or {}), country_geoip=geo,
                policy_country_groups_type=kind, policy_special_groups_type=kind)


def body(values, source=SOURCE):
    result=dict(values)
    if values.get('yaml_source')=='custom':result['yaml_file']=(io.BytesIO(source.encode()),'custom.yaml')
    return result


def apply_diff(source, diff):
    """Reconstruct generated text from the public unified response, not internals."""
    if not diff:return source
    original=source.splitlines(keepends=True); output=[]; pos=0; previous=''
    for line in diff.splitlines(keepends=True)[2:]:
        if line.startswith('@@ '):
            match=re.match(r'@@ -(\d+)(?:,(\d+))? \+',line)
            start=int(match[1])-(0 if match[2]=='0' else 1)
            output.extend(original[pos:start]);pos=start
        elif line.startswith('\\ No newline'):
            if previous in ('+',' ') and output:output[-1]=output[-1][:-1]
        elif line[0] in (' ','+','-'):
            previous=line[0]
            if previous in (' ','+'):output.append(line[1:])
            if previous in (' ','-'):pos+=1
    output.extend(original[pos:])
    return ''.join(output)


@pytest.mark.parametrize('source',['custom','default'])
@pytest.mark.parametrize('mode',['replace','merge'])
@pytest.mark.parametrize('kind',['preserve','select','url-test','fallback','load-balance'])
@pytest.mark.parametrize('manual',[False,True])
@pytest.mark.parametrize('geo',['off','literal-ip'])
def test_exact_preview_response_matches_subsequent_generate(web,logged_in,readers,source,mode,kind,manual,geo):
    web.geoip_store.upload('country.mmdb',io.BytesIO(b'SYNTHETIC:SG'))
    batch='Opaque|'+LINK.replace('example.com','8.8.8.8')
    key=generator.parse_form_nodes({'batch_nodes':batch})['preview'][0]['key']
    edits={key:{'name':'Edited Ω','country':'TW'}} if manual else {}
    values=fields(source,kind,edits,geo,batch)
    values['node_update_mode']=mode
    values['special_groups']=web.DEFAULT_SPECIAL_GROUPS[:2]
    response=post(logged_in,ROUTE,body(values))
    assert response.status_code==200,response.json
    assert response.headers['Cache-Control']=='no-store'
    assert response.headers['Referrer-Policy']=='no-referrer'
    assert set(response.json)=={'ok','changed','diff','summary'}
    actual_source=SOURCE if source=='custom' else Path(web.DEFAULT_YAML_PATH).read_text()
    would_be=apply_diff(actual_source,response.json['diff']).encode()
    generated=post(logged_in,'/process',body(values));assert generated.status_code==302
    with logged_in.session_transaction() as session:context=session['page_context']
    assert not context['error_messages']
    actual=Path(web.DIR_OUTPUTS,context['output_filename']).read_bytes()
    assert actual==would_be
    assert response.json['summary']=={k:context['result'][k] for k in response.json['summary']}
    assert logged_in.get(context['download_url']).data==actual


@pytest.mark.parametrize('source',['custom','default'])
def test_known_before_refactor_generate_output_identical(web,logged_in,source):
    response=post(logged_in,'/process',body(fields(source)))
    assert response.status_code==302
    with logged_in.session_transaction() as session:name=session['page_context']['output_filename']
    assert hashlib.sha256(Path(web.DIR_OUTPUTS,name).read_bytes()).hexdigest()==BEFORE_HASHES[source]


@pytest.mark.parametrize('source',[SOURCE.replace('\n','\r\n'),SOURCE.rstrip('\n'),'\ufeff'+SOURCE])
def test_source_line_endings_and_missing_newline_exact(web,logged_in,source):
    values=fields()
    response=post(logged_in,ROUTE,body(values,source));assert response.status_code==200
    post(logged_in,'/process',body(values,source))
    with logged_in.session_transaction() as session:name=session['page_context']['output_filename']
    assert apply_diff(source,response.json['diff']).encode()==Path(web.DIR_OUTPUTS,name).read_bytes()


def test_latest_input_not_cached_and_no_change(web,logged_in):
    post(logged_in,'/parse-nodes',fields())
    values=fields(batch='US|Latest|'+LINK)
    first=post(logged_in,ROUTE,body(values));assert first.status_code==200
    generated=apply_diff(SOURCE,first.json['diff'])
    assert 'Latest' in generated and 'Test' not in generated
    response=post(logged_in,ROUTE,body(values,generated))
    assert response.status_code==200 and response.json['changed'] is False and response.json['diff']==''


@pytest.mark.parametrize('case',['uri','duplicate','group-conflict','malformed','structure','policy','missing-custom','extension'])
def test_preview_generate_validation_parity_no_secret_traceback(web,logged_in,case,caplog):
    values=fields();source=SOURCE
    if case=='uri':values['batch_nodes']='US|Oops|vless://PRIVATE-invalid'
    if case=='duplicate':values['batch_nodes']+='\n'+values['batch_nodes']
    if case=='group-conflict':source=SOURCE.replace('name: custom','name: 🇺🇸 Test')
    if case=='malformed':source='[PRIVATE-body'
    if case=='structure':source='proxies: PRIVATE-body\n'
    if case=='policy':values['policy_country_groups_type']='PRIVATE-policy'
    if case=='missing-custom':payload=dict(values)
    else:payload=body(values,source)
    if case=='extension':payload['yaml_file']=(io.BytesIO(source.encode()),'secret.txt')
    preview=post(logged_in,ROUTE,payload)
    assert preview.status_code==400 and preview.json['ok'] is False
    if case=='missing-custom':payload=dict(values)
    else:payload=body(values,source)
    if case=='extension':payload['yaml_file']=(io.BytesIO(source.encode()),'secret.txt')
    actual=post(logged_in,'/process',payload)
    assert actual.status_code==400
    assert preview.json['error'] in actual.text or all(e in actual.text for e in preview.json['error'].split(' 第 '))
    assert not list(Path(web.DIR_OUTPUTS).iterdir())
    assert all(secret not in caplog.text for secret in ('PRIVATE-invalid','PRIVATE-body','PRIVATE-policy'))
    assert 'Traceback' not in preview.text and str(web.BASE_DIR) not in preview.text


def snapshot(web):
    result={}
    for name in ('uploads','outputs','backups','state'):
        root=Path(web.BASE_DIR,name)
        for path in [root,*root.rglob('*')]:
            stat=path.lstat()
            result[str(path.relative_to(web.BASE_DIR))]=(path.read_bytes() if path.is_file() else None,stat.st_mode,stat.st_mtime_ns,stat.st_ino)
    for name in ('.env','INSTALLATION.json','HTTPS_DEPLOYMENT.json'):
        path=Path(web.BASE_DIR,name)
        result[name]=path.read_bytes() if path.exists() else None
    return result


@pytest.mark.parametrize('mode',['replace','merge'])
def test_100_previews_no_business_mutation_cleanup_network_or_commands(web,logged_in,readers,monkeypatch,caplog,mode):
    csrf=token(logged_in)
    web.geoip_store.upload('country.mmdb',io.BytesIO(b'SYNTHETIC:SG'))
    web.geoip_store.lock.unlink() # Read-only lookup cannot recreate even a missing lock.
    for name in ('fixed_subscriptions.json','node_health.json','proxy_health.json','notifications.json','temporary_links.json'):
        path=Path(web.DIR_STATE,name);path.write_bytes(b'PRIVATE business sentinel');path.chmod(0o600)
    for directory in (web.DIR_UPLOADS,web.DIR_OUTPUTS,web.DIR_BACKUPS):
        path=Path(directory,'expired.yaml');path.write_bytes(b'expired');os.utime(path,(1,1))
    os.utime(web.CLEANUP_MARKER,(1,1))
    before=snapshot(web)
    def forbidden(*args,**kwargs):raise AssertionError('forbidden business side effect')
    for owner,name in [(web,'cleanup_old_files'),(generator,'generate'),(yaml_utils,'backup_yaml'),
                       (yaml_utils,'save_new_output'),(socket,'getaddrinfo'),(socket,'create_connection'),(subprocess,'run')]:
        monkeypatch.setattr(owner,name,forbidden)
    caplog.clear()
    for i in range(100):
        values=fields(geo='literal-ip',batch='Opaque|'+LINK.replace('example.com','8.8.8.8'))
        values['node_update_mode']=mode
        values['csrf_token']=csrf
        response=logged_in.post(ROUTE,data=body(values))
        assert response.status_code==200,response.json
        assert '🇸🇬 Opaque' in response.json['diff']
    assert snapshot(web)==before
    assert not web.geoip_store.lock.exists()
    assert '<script>' not in caplog.text and '11111111-1111' not in caplog.text
    for path in Path(web.BASE_DIR,'logs').rglob('*'):
        if path.is_file():assert b'<script>' not in path.read_bytes() and LINK.encode() not in path.read_bytes()


@pytest.mark.parametrize('mode',['replace','merge'])
def test_parallel_preview_requests_isolated(web,logged_in,mode):
    csrf=token(logged_in);cookie=logged_in.get_cookie('session').value;before=snapshot(web)
    def one(index):
        with web.app.test_client() as client:
            client.set_cookie('session',cookie)
            values=fields(batch=f'US|Unique-{index}-END|'+LINK);values['csrf_token']=csrf
            values['node_update_mode']=mode
            response=client.post(ROUTE,data=body(values))
            assert response.status_code==200
            return response.json['diff']
    with ThreadPoolExecutor(max_workers=8) as pool:results=list(pool.map(one,range(16)))
    for i,text in enumerate(results):
        assert f'Unique-{i}-END' in text
        assert all(f'Unique-{j}-END' not in text for j in range(16) if j!=i)
    assert snapshot(web)==before


def test_route_auth_csrf_post_only_and_private_errors(web,logged_in):
    anonymous=web.app.test_client()
    assert post(anonymous,ROUTE,fields()).status_code==401
    assert logged_in.get(ROUTE).status_code==405
    for data in ({},{'csrf_token':'invalid'}):
        response=logged_in.post(ROUTE,data=data)
        assert response.status_code==400 and response.json['code']=='csrf_failed'
        assert response.headers['Cache-Control']=='no-store'
    web.app.config['MAX_CONTENT_LENGTH']=32
    response=logged_in.post(ROUTE,data={'batch_nodes':'x'*1024})
    assert response.status_code==413 and response.json['ok'] is False
    assert response.headers['Cache-Control']=='no-store'


@pytest.mark.parametrize('budget',['source','form','generated','lines','nodes','groups','diff','response'])
def test_resource_limits_explicit_and_generate_still_available(web,logged_in,monkeypatch,budget):
    values=fields();source=SOURCE
    if budget=='source':monkeypatch.setattr(yaml_diff,'MAX_YAML_BYTES',len(source.encode())-1)
    if budget=='form':monkeypatch.setattr(yaml_diff,'MAX_FORM_BYTES',1)
    if budget=='generated':source='{}\n';monkeypatch.setattr(yaml_diff,'MAX_YAML_BYTES',50)
    if budget=='lines':monkeypatch.setattr(yaml_diff,'MAX_LINES',1)
    if budget=='nodes':monkeypatch.setattr(yaml_diff,'MAX_NODES',0)
    if budget=='groups':monkeypatch.setattr(yaml_diff,'MAX_SOURCE_GROUPS',0)
    if budget=='diff':monkeypatch.setattr(yaml_diff,'MAX_DIFF_BYTES',10)
    if budget=='response':monkeypatch.setattr(yaml_diff,'MAX_RESPONSE_BYTES',10)
    response=post(logged_in,ROUTE,body(values,source))
    assert response.status_code==400 and response.json['error']==yaml_diff.TOO_LARGE
    assert 'diff' not in response.json
    assert post(logged_in,'/process',body(values,source)).status_code==302


def test_diff_byte_boundary_inclusive(monkeypatch):
    expected=yaml_diff.unified('old\n','new Ω\n')
    monkeypatch.setattr(yaml_diff,'MAX_DIFF_BYTES',len(expected.encode()))
    assert yaml_diff.unified('old\n','new Ω\n')==expected
    monkeypatch.setattr(yaml_diff,'MAX_DIFF_BYTES',len(expected.encode())-1)
    with pytest.raises(yaml_diff.PreviewLimitError):yaml_diff.unified('old\n','new Ω\n')


@pytest.mark.parametrize('error',[ValueError,RuntimeError,OSError])
@pytest.mark.parametrize('stage',['input','transform'])
def test_unexpected_exception_never_echoed_logged_or_saved(web,logged_in,monkeypatch,caplog,error,stage):
    def failure(*args,**kwargs):raise error('PRIVATE exception /root/secret uuid=TEST_ONLY')
    monkeypatch.setattr(web,'parse_form_nodes',failure) if stage=='input' else monkeypatch.setattr(yaml_diff,'preview',failure)
    response=post(logged_in,ROUTE,body(fields()))
    assert response.status_code==400 and response.json['error']==yaml_diff.PROCESSING_ERROR
    assert 'PRIVATE exception' not in response.text+caplog.text
    assert not list(Path(web.DIR_OUTPUTS).iterdir())


def test_geoip_existing_lock_readonly_and_busy_fail_open_match_generate(web,logged_in,readers):
    from core.state import file_lock
    web.geoip_store.upload('country.mmdb',io.BytesIO(b'SYNTHETIC:SG'))
    before=web.geoip_store.lock.stat()
    values=fields(geo='literal-ip',batch='Opaque|'+LINK.replace('example.com','8.8.8.8'))
    response=post(logged_in,ROUTE,body(values));assert response.status_code==200
    assert '🇸🇬 Opaque' in response.json['diff']
    assert web.geoip_store.lock.stat()==before
    with file_lock(web.geoip_store.lock,blocking=False):
        preview=post(logged_in,ROUTE,body(values));assert preview.status_code==200
        post(logged_in,'/process',body(values))
        with logged_in.session_transaction() as session:name=session['page_context']['output_filename']
        assert apply_diff(SOURCE,preview.json['diff']).encode()==Path(web.DIR_OUTPUTS,name).read_bytes()
        assert '🌐 Opaque' in preview.json['diff']


@pytest.mark.parametrize('kind',['fifo','symlink','directory'])
def test_geoip_unsafe_lock_preview_fail_open_no_repair(web,logged_in,readers,kind):
    web.geoip_store.upload('country.mmdb',io.BytesIO(b'SYNTHETIC:SG'));path=web.geoip_store.lock
    path.unlink()
    if kind=='fifo':os.mkfifo(path,0o600)
    elif kind=='symlink':path.symlink_to(web.geoip_store.settings)
    else:path.mkdir(mode=0o700)
    before=path.lstat()
    response=post(logged_in,ROUTE,body(fields(geo='literal-ip',batch='Opaque|'+LINK.replace('example.com','8.8.8.8'))))
    assert response.status_code==200 and '🌐 Opaque' in response.json['diff']
    assert path.lstat()==before


def test_source_budget_exact_utf8_and_invalid_encoding(monkeypatch):
    text='Ω\n'
    monkeypatch.setattr(yaml_diff,'MAX_YAML_BYTES',len(text.encode()))
    assert yaml_diff.read_source(io.BytesIO(text.encode()))==text
    with pytest.raises(yaml_diff.PreviewLimitError):yaml_diff.read_source(io.BytesIO((text+'x').encode()))
    with pytest.raises(yaml_diff.PreviewValidationError):yaml_diff.read_source(io.BytesIO(b'\xff'))


def test_multipart_private_spool_closed_after_preview(web,logged_in,monkeypatch):
    original=yaml_diff.read_source;seen=[]
    def inspect(stream):
        assert stream._rolled # Werkzeug uses a private spool for a >512 KiB part.
        seen.append((stream,os.fstat(stream.fileno()).st_mode & 0o777))
        return original(stream)
    monkeypatch.setattr(yaml_diff,'read_source',inspect)
    response=post(logged_in,ROUTE,body(fields(),'#'+'W'*(600*1024)+'\n'+SOURCE))
    assert response.status_code==400 and response.json['error']==yaml_diff.TOO_LARGE
    assert len(seen)==1 and seen[0][1]==0o600 and seen[0][0].closed
    assert not list(Path(web.DIR_UPLOADS).iterdir()) and not list(Path(web.DIR_OUTPUTS).iterdir())


def test_corrupt_auth_fails_closed_private_json_without_rewriting(web,logged_in):
    csrf=token(logged_in)
    path=Path(web.DIR_STATE,'auth.json');path.write_bytes(b'PRIVATE auth corrupt')
    response=logged_in.post(ROUTE,data={**fields(), 'csrf_token':csrf})
    assert response.status_code==503 and response.json['ok'] is False
    assert response.headers['Cache-Control']=='no-store' and 'PRIVATE' not in response.text
    assert path.read_bytes()==b'PRIVATE auth corrupt'


@pytest.mark.parametrize('source',[
    'x-one: &PRIVATE_ANCHOR first\nx-two: &PRIVATE_ANCHOR second\n'+SOURCE,
    '%YAML 1.1\n---\nx-float: 1e3\n'+SOURCE,
])
def test_nonfatal_yaml_warnings_private_and_generate_bytes_unchanged(web,logged_in,source,caplog,capsys):
    import warnings
    values=fields()
    with warnings.catch_warnings(record=True) as records:
        warnings.simplefilter('always')
        preview=post(logged_in,ROUTE,body(values,source))
    assert preview.status_code==200 and not records
    output=capsys.readouterr()
    assert 'PRIVATE_ANCHOR' not in output.out+output.err+caplog.text
    with warnings.catch_warnings(record=True) as original_records:
        warnings.simplefilter('always')
        generated=post(logged_in,'/process',body(values,source))
    assert generated.status_code==302 and original_records # No global warning suppression.
    with logged_in.session_transaction() as session:name=session['page_context']['output_filename']
    assert apply_diff(source,preview.json['diff']).encode()==Path(web.DIR_OUTPUTS,name).read_bytes()


def test_private_parser_does_not_change_dependency_constructor_or_warning_filters():
    import warnings
    original=yaml_utils.get_yaml_engine().constructor.yaml_constructors['tag:yaml.org,2002:float']
    filters=warnings.filters[:]
    engine=yaml_diff.private_yaml_engine()
    assert engine.constructor.yaml_constructors['tag:yaml.org,2002:float'] is not original
    assert yaml_utils.get_yaml_engine().constructor.yaml_constructors['tag:yaml.org,2002:float'] is original
    assert warnings.filters==filters
