"""Keep standalone curl|bash scripts in sync with their reviewed Python source."""
from pathlib import Path
import sys

ROOT = Path(__file__).resolve().parents[1]


def render(mode):
    source = (ROOT / 'scripts/remote_lifecycle.py').read_text()
    return ('#!/usr/bin/env bash\nset -euo pipefail\n'
            '# Generated by scripts/build_bootstraps.py; edit scripts/remote_lifecycle.py.\n'
            'command -v python3 >/dev/null || { echo "python3 is required." >&2; exit 1; }\n'
            'command -v curl >/dev/null || { echo "curl is required." >&2; exit 1; }\n'
            f'python3 - {mode} "$@" <<\'BOOTSTRAP_PY\'\n' + source + 'BOOTSTRAP_PY\n')


def main():
    for mode in ('install', 'update'):
        path = ROOT / f'remote-{mode}.sh'
        expected = render(mode)
        if '--check' in sys.argv:
            if not path.exists() or path.read_text() != expected:
                sys.exit(f'{path.name} is out of date; run scripts/build_bootstraps.py.')
        else:
            path.write_text(expected)


if __name__ == '__main__':
    main()
